### ISSUE TITLE
Clay Latex Bowl can't burn in pit killn

### ISSUE THREAD

**Issue by LaysDragon** [Shurgent/TFCTech#10]
Clay Latex Bowl can't burn in pit killn
After burning ,Clay Latex Bowl still not what we need to use(still is Clay Latex Bowl/0 not Clay Latex Bowl/1).
(sory for my bed English)

**Comment by Shurgent** [comment]
This is weird. I forgot to add pit kiln recipe of latex bowl. It is strange that this error was discovered only now!
Thanks for bug report! I added missing recipe. Expect in next update.
