### ISSUE TITLE
GregTech/NEI/TFCTech Recipe-Viewing Crash

### ISSUE THREAD

**Issue by RandomIntel** [Shurgent/TFCTech#11]
I'm currently trying to integrate GregTech into TFC using TFCTech. The crash is experienced when I press [R] or [U] over an item (to find the Recipes or Uses, respectively) while using NEI. I have confirmed that this happens when I have these mods loaded:
- TerraFirmaCraft 0.79.29.922
- TFCTech 0.2.8 A13-HOTFIX2
- GregTech 6.03.23
- industrialcraft2 2.2.826-experimental
- industrialcraft2 2.2.826-experimental-api
- NEI 1.0.5.120-universal
- CodeChickenCore 1.0.7.47-universal
  
  When I try to look for the Recipes/Uses for an item, it freezes for around ~1 second, cuts to the loading screen, says "Shutting down internal server" (as it says when Saving and Quitting a world) and then closes, showing the Crash-Report.

Here is the crash report:
[crash-2016-10-03_12.50.03-client.txt](https://github.com/Shurgent/TFCTech/files/508894/crash-2016-10-03_12.50.03-client.txt)

**Comment by Shurgent** [comment]
I hope it fixed. If not, please reopen the issue.
