### ISSUE TITLE
Using Lime Paint Colors Sheep Incorrectly

### ISSUE THREAD

**Issue by RandomIntel** [Shurgent/TFCTech#12]
[Using Blue Lime Paint always colors them green.](https://cloud.githubusercontent.com/assets/22619104/19415631/43ea1ad6-9333-11e6-93c7-2f5ecce1817b.png)

[Using Yellow Lime Paint always colors them purple.](https://cloud.githubusercontent.com/assets/22619104/19415640/8ec222ba-9333-11e6-873d-46ca3c7350e7.png)

This is the case with all 16 colors. I have noticed no pattern in the crossover of colors. This bug does not happen with vanilla/TFC dyes

**Comment by Shurgent** [comment]
This is weird. OK, I'll see what can be the reason for this strange behavior ...

**Comment by Shurgent** [comment]
I found a bug. Will be fixed in the next update.

**Comment by Shurgent** [comment]
Fixed.
