### ISSUE TITLE
NEI recipe CTD

### ISSUE THREAD

**Issue by KillAshley** [Shurgent/TFCTech#13]
Noticed a CTD bug in NEI with TFCTech. Trying to view recipes for certain objects (such as unshaped black, blue & red steel) causes a complete CTD. This only occurs when TFCTech is installed unfortunately.

Installed mods to reproduce;

CodeChickenCore 1.0.1.47
NotEnoughItems 1.0.5.120
TerraFirmaCraftNEIPlugin 1.5.3.25
TerraFirmaCraft 0.79.29.922
TFCTech 0.2.8-A13-HOTFIX2

Crash Log;
http://pastebin.com/NB41eq0P

**Comment by Shurgent** [comment]
How did you run the game in general? NotEnoughItems 1.0.5.120 requires CodeChickenCore 1.0.7+ !!!
But I suspect that this is a typo and you use version 1.0.**7**.47
Crash reproduced. Interestingly, in the Eclipse debugger, the game does not crash. I would look for the cause of this behavior ...

**Comment by KillAshley** [comment]
haha yeah 1.0.7.47, my bad! at least you could figure the version out even with my caffeine deprived mistake!

**Comment by Shurgent** [comment]
I found the cause of crash. The error only occurs if Buildcraft is not installed. Bug fixed, expect in the next update.

**Comment by Shurgent** [comment]
Fixed.
