### ISSUE TITLE
Induction smelter compatibility issue with tfctweaker

### ISSUE THREAD

**Issue by wormzjl** [Shurgent/TFCTech#16]
As per title

Also if the smelting for something is removed using tfctweaker, it can also be smelted in the induction smelter, does it uses a static list for smeltable stuffs instead of having a dynamic reference on TFC?

**Comment by Shurgent** [comment]
I can not reproduce the issue described in the title. And no, it is not uses a static list for smeltable stuffs. It uses com.bioxx.tfc.api.HeatRegistry
https://github.com/Shurgent/TFCTech/blob/master/src/main/java/ua/pp/shurgent/tfctech/items/ItemHeat.java#L17

Describe in more detail what you are doing.

**Comment by wormzjl** [comment]
Actually I tries to use this function from TFCTweaker to prevent some stuff from being smelted

mods.Terrafirmacraft.ItemHeat.removeRecipe(InputStack);

It works for TFC fire pit and forge, but they can still be smelted in the induction smelter

**Comment by Shurgent** [comment]
I don't know how TFCTweaker works. I suppose it's not TFCTech issue...

**Comment by wormzjl** [comment]
Using the induction forge from TFC engineers mod have no such issue, so I guess it's a problem of implementation?
This is how tfctweaker does it
https://github.com/StrayWolfe/TFC-Tweaker/blob/981d2886e0a5c33c6096aedf647819d4e7d4a561/src/main/java/straywolfe/tfctweaker/handlers/ItemHeat.java#L163

**Comment by wormzjl** [comment]
Ok, just found out that if I remove any heating items with tfctweaker, it can be smelted in the induction smelter without any heat

**Comment by Shurgent** [comment]
Induction Smelter works exactly the same as TFC Crucible:
https://github.com/Shurgent/TFCTech/blob/master/src/main/java/ua/pp/shurgent/tfctech/tileentities/TEInductionSmelter.java#L260
It uses TFC_ItemHeat.isCookable() method from com.bioxx.tfc.api, wich uses HeatRegistry, same as TFC-Tweaker.
https://github.com/Deadrik/TFCraft/blob/master/src/API/com/bioxx/tfc/api/TFC_ItemHeat.java#L177
Does TFC Crucible have such issue?

**Comment by wormzjl** [comment]
Ok seems this does not work well with the crucible.
Thank you for looking, I'll report to the owner of TFCtweaker
