### ISSUE TITLE
Crash on spliting iron

### ISSUE THREAD

**Issue by LightningSh0ck** [Shurgent/TFCTech#6]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at ua.pp.shurgent.tfctech.handlers.AnvilCraftingHandler.onAnvilCrafting(AnvilCraftingHandler.java:16)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_345_AnvilCraftingHandler_onAnvilCrafting_AnvilCraftEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at com.bioxx.tfc.TileEntities.TEAnvil.func_145845_h(TEAnvil.java:127)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ua.pp.shurgent.tfctech.handlers.AnvilCraftingHandler.onAnvilCrafting(AnvilCraftingHandler.java:16)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_345_AnvilCraftingHandler_onAnvilCrafting_AnvilCraftEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at com.bioxx.tfc.TileEntities.TEAnvil.func_145845_h(TEAnvil.java:127)
    at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
    Name: TerraAnvil // com.bioxx.tfc.TileEntities.TEAnvil
    Block type: ID #226 (tile.Anvil // com.bioxx.tfc.Blocks.Devices.BlockAnvil)
    Block data value: 11 / 0xB / 0b1011
    Block location: World: (6363,148,-6304), Chunk: (at 11,9,0 in 397,-394; contains blocks 6352,0,-6304 to 6367,255,-6289), Region: (12,-13; contains chunks 384,-416 to 415,-385, blocks 6144,0,-6656 to 6655,255,-6145)
    Actual block type: ID #226 (tile.Anvil // com.bioxx.tfc.Blocks.Devices.BlockAnvil)
    Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
    Level name: New World
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 5766521687008856365
    Level generator: ID 00 - TFCDefault, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (6208,152,-6108), Chunk: (at 0,9,4 in 388,-382; contains blocks 6208,0,-6112 to 6223,255,-6097), Region: (12,-12; contains chunks 384,-384 to 415,-353, blocks 6144,0,-6144 to 6655,255,-5633)
    Level time: 6773105 game time, 7098271 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 27270 (now: false), thunder time: 9237 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 232912816 bytes (222 MB) / 1634205696 bytes (1558 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 13, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 44 mods loaded, 44 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   tfc_coremod{0.79.29} [TFC[coremod]](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJAAAA   OpenComputers|Core{1.5.22.46} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHIJAAAA   terrafirmacraft{0.79.29} [TerraFirmaCraft]([1.7.10]TerraFirmaCraft-0.79.29.922.jar) 
    UCHIJAAAA   TFC-Tweaks{0.4.0.17} [TFC-Tweaks](TFC-Tweaks-1.7.10-0.4.0.17.jar) 
    UCHIJAAAA   tfcm{0.11.1} [TerraMisc]([1.7.10]TerraMisc-0.11.1.jar) 
    UCHIJAAAA   tfccellars{1.1} [CellarsAddon]([1.7.10]TFCCellarsAddon-1.1.jar) 
    UCHIJAAAA   weightingscales{1.0} [TFC Scales]([1.7.10]TFCScales-1.0.1.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.17} [BuildCraft](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.17} [BC Silicon](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.17} [BC Transport](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.17} [BC Builders](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.17} [BC Energy](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.17} [BC Robotics](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.17} [BC Factory](buildcraft-7.1.17.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.5} [BuildCraft Compat](buildcraft-compat-7.1.5.jar) 
    UCHIJAAAA   IC2{2.2.822-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.822-experimental.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.3.126} [Logistics Pipes](logisticspipes-0.9.3.126.jar) 
    UCHIJAAAA   OpenComputers{1.5.22.46} [OpenComputers](OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
    UCHIJAAAA   Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
    UCHIJAAAA   tfctech{0.2.7-A12} [Shurgent's TFCTech Addon]([1.7.10]TFCTech-0.2.7-A12.jar) 
    UCHIJAAAA   animalcrate{0.01} [AnimalCrate](animalcrate-0.1.jar) 
    UCHIJAAAA   MovingWorld{1.7.10-1.8.1} [Moving World](movingworld-1.7.10-1.8.1.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus](archimedesshipsplus-1.7.10-1.8.1.jar) 
    UCHIJAAAA   customitems{1.0.9b} [Meta Mod: Custom Items](customitems-1.0.9_beta_1.7.10.jar) 
    UCHIJAAAA   IC2NuclearControl{2.4.1a} [Nuclear Control 2](IC2NuclearControl-2.4.1a.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAAAA   MTRM{1.0} [MineTweakerRecipeMaker](MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
    UCHIJAAAA   neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJAAAA   OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJAAAA   OpenPeripheralCore{1.3} [OpenPeripheralCore](OpenPeripheralCore-1.7.10-1.3.jar) 
    UCHIJAAAA   OpenPeripheral{0.5.1} [OpenPeripheralAddons](OpenPeripheralAddons-1.7.10-0.5.1.jar) 
    UCHIJAAAA   OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration](OpenPeripheralIntegration-1.7.10-0.5.jar) 
    UCHIJAAAA   PowerConverters{1.7.10_3.2.1} [Power Converters](PowerConverters-1.7.10_3.2.1.jar) 
    UCHIJAAAA   StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHIJAAAA   TerraFirmaCraftNEIplugin{1.5.3.25} [TerraFirmaCraftNEIplugin](TerraFirmaCraftNEIplugin-1.7.10-1.5.3.25.jar) 
    UCHIJAAAA   tfcrailcraft{0.2.0} [TFC Railcraft Compatibility](tfcrailcraft-0.2.0.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    TFC-Tweaks: PLEASE TRY TO START THE GAME AT LEAST TWICE. The load order modifications we do only kick in after a reload.
    TFC-Tweaks-ASM: FluidContainerRegistryCT: 3 / 3; FluidRegistryCT: 6 / 6
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Shurgent** [comment]
Fixed
