### ISSUE TITLE
Induction Smelter Dupe

### ISSUE THREAD

**Issue by StrayWolfe** [Shurgent/TFCTech#8]
The induction smelter is "duplicated" when it is harvested with a pick in survival mode. You might want to override the harvestBlock method to stop that dupe. Looks like it is dropping your nbt loaded item specified in the breakBlock method and it is also running the default behavior of dropping the block when the harvestBlock method fires.

**Comment by Shurgent** [comment]
I forgot to override dropBlockAsItem method. Fixed. Expect a hotfix soon.

**Comment by Shurgent** [comment]
Fixed
