### ISSUE TITLE
Induction Smelter GUI updates

### ISSUE THREAD

**Issue by StrayWolfe** [Shurgent/TFCTech#9]
Looks like the GUI for the induction smelter is not updating the currentAlloy info from the TEInductionSmelter during the first opening of the GUI. Reopening the GUI resolves this issue. To replicate, get a fresh induction smelter, place it and open the GUI. Place one ingot in at a time without closing the GUI and you will see that is does not update. You should be able to fix this by including the currentAlloy in the detectAndSendChanges method of the ContainerInductionSmelter. It also looks like updateGui method of the TEInductionSmelter would be redundant with the detectAndSendChanges method.

**Comment by Shurgent** [comment]
Fixed.
